global:
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: smtp.gmail.com:587
  smtp_from: msgopi6626@gmail.com
  smtp_auth_username: msgopi6626@gmail.com
  # Use an App Password here, NOT your main account password
  smtp_auth_password: dgrkyqgauodmmvgg
  smtp_auth_identity: msgopi6626@gmail.com
  smtp_require_tls: true # Gmail requires TLS
  resolve_timeout: 5m

route:
  receiver: 'gmail-alerts'
  # Other routing options (group_by, group_wait, etc.) can be added here.

receivers:
- name: 'gmail-alerts'
  email_configs:
  - to: sivagopi4717@gmail.com
    # from, smarthost, auth_username, auth_password, etc. can be defined here
    # to override the global settings if needed.
    send_resolved: true # Send a notification when the alert is resolved
    # You can also use a custom HTML template:
    # html: '{{ template "email.tmpl" . }}' 
    headers :
      Subject: '[{{ .Status | toUpper }}] {{ .CommonLabels.alertname }} ({{ .CommonLabels.severity }})'